// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEt40C66c0_2dFqGTaz-lWOGm64yUe6H0',
    appId: '1:154097110008:web:4c7679ad31afaabf37240d',
    messagingSenderId: '154097110008',
    projectId: 'shaheen-namaz',
    authDomain: 'shaheen-namaz.firebaseapp.com',
    storageBucket: 'shaheen-namaz.appspot.com',
    measurementId: 'G-PY44R6M83J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWRJE_hFUQaldZ32zwwbIb8uywqSktkM',
    appId: '1:154097110008:android:57204ed7e0ddfda637240d',
    messagingSenderId: '154097110008',
    projectId: 'shaheen-namaz',
    storageBucket: 'shaheen-namaz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA701Bcgw70LHnREU3o44TOBLHRG4br6rs',
    appId: '1:154097110008:ios:b0b1d6732d73fc0c37240d',
    messagingSenderId: '154097110008',
    projectId: 'shaheen-namaz',
    storageBucket: 'shaheen-namaz.appspot.com',
    iosBundleId: 'com.stouch.shaheenhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA701Bcgw70LHnREU3o44TOBLHRG4br6rs',
    appId: '1:154097110008:ios:bdde736f387a5c6637240d',
    messagingSenderId: '154097110008',
    projectId: 'shaheen-namaz',
    storageBucket: 'shaheen-namaz.appspot.com',
    iosBundleId: 'com.example.shaheenHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEt40C66c0_2dFqGTaz-lWOGm64yUe6H0',
    appId: '1:154097110008:web:4c7679ad31afaabf37240d',
    messagingSenderId: '154097110008',
    projectId: 'shaheen-namaz',
    authDomain: 'shaheen-namaz.firebaseapp.com',
    storageBucket: 'shaheen-namaz.appspot.com',
    measurementId: 'G-PY44R6M83J',
  );
}
